CREATE DATABASE IF NOT EXISTS pet_db 
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE pet_db;

CREATE TABLE IF NOT EXISTS pet_stats (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  hunger INT NOT NULL DEFAULT 100 COMMENT '饱食度',
  happiness INT NOT NULL DEFAULT 100 COMMENT '愉悦度',
  intimacy INT NOT NULL DEFAULT 0 COMMENT '亲密度',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO pet_stats (hunger, happiness, intimacy) VALUES (100, 100, 0);